#:kivy 1.9.0

<RogueSprite>:
    Label:
        font_size: 20
        center: self.parent.center
        text: str("@")


<PyRogueGame>:
    player: rogue_sprite
    keypress_label: keypress_label

    RogueSprite:
        id: rogue_sprite
        center: self.parent.center

    Label:
        id: keypress_label
        font_size: 12
        center_x: root.width * 3 / 4
        top: root.top - 50
