#:kivy 1.9.0


<MapTile>:
    tile: tile
    width: 20
    height: 20

    Label:
        id: tile
        font_size: 10
        text: str(".")


<BaseSprite>:
    font_size: 20
    text: str("@")


<PyRogueGame>:
    keypress_label: keypress_label
    width: 20 * 24
    height: 20 * 24

    Label:
        id: keypress_label
        font_size: 12
        center_x: root.width * 3 / 4
        top: root.top - 50
